package com.java_template.application.entity.mail.version_1; // replace {entityName} with actual entity name in lowercase

import com.java_template.common.workflow.CyodaEntity;
import com.java_template.common.workflow.OperationSpecification;
import org.cyoda.cloud.api.event.common.ModelSpec;
import lombok.Data;

import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

@Data
public class Mail implements CyodaEntity {
    public static final String ENTITY_NAME = "Mail";
    public static final Integer ENTITY_VERSION = 1;

    // Required fields per functional requirements
    private String technicalId; // generated by platform
    private Boolean isHappy; // system-determined
    private List<String> mailList;
    private String state;
    private Map<String, Object> deliveryStatus; // attempts, lastAttempt, status, lastError, perRecipient
    private String createdAt;
    private String updatedAt;

    private static final Pattern SIMPLE_EMAIL = Pattern.compile("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$");

    public Mail() {}

    @Override
    public OperationSpecification getModelKey() {
        ModelSpec modelSpec = new ModelSpec();
        modelSpec.setName(ENTITY_NAME);
        modelSpec.setVersion(ENTITY_VERSION);
        return new OperationSpecification.Entity(modelSpec, ENTITY_NAME);
    }

    @Override
    public boolean isValid() {
        // Validate that mailList is present and contains at least one valid email
        if (mailList == null || mailList.isEmpty()) {
            return false;
        }
        return mailList.stream().allMatch(addr -> addr != null && !addr.isBlank() && SIMPLE_EMAIL.matcher(addr).matches());
    }
}
