package com.java_template.application.controller;

import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.java_template.application.entity.AdoptionRequest;
import com.java_template.application.entity.Pet;
import com.java_template.application.entity.PetJob;
import com.java_template.common.service.EntityService;
import com.java_template.common.util.Condition;
import com.java_template.common.util.SearchConditionRequest;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;

import static com.java_template.common.config.Config.*;

@RestController
@RequestMapping(path = "/entities")
@RequiredArgsConstructor
@Slf4j
public class Controller {

    private static final Logger logger = LoggerFactory.getLogger(Controller.class);

    private final EntityService entityService;

    // PetJob endpoints

    @PostMapping("/petJobs")
    public ResponseEntity<?> createPetJob(@RequestBody PetJob petJob) throws Exception {
        if (petJob == null || petJob.getSourceUrl() == null || petJob.getSourceUrl().isBlank()) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("sourceUrl is required");
        }
        petJob.setJobId(UUID.randomUUID().toString());
        petJob.setCreatedAt(LocalDateTime.now());
        petJob.setStatus("PENDING");
        // technicalId generated by addItem
        CompletableFuture<UUID> idFuture = entityService.addItem("PetJob", ENTITY_VERSION, petJob);
        UUID technicalId = idFuture.get();
        petJob.setTechnicalId(technicalId);

        return ResponseEntity.status(HttpStatus.CREATED).body(petJob);
    }

    @GetMapping("/petJobs/{id}")
    public ResponseEntity<?> getPetJob(@PathVariable String id) throws Exception {
        // id is string but entityService expects technicalId (UUID)
        // We'll search by "id" field (string) using condition
        SearchConditionRequest condition = SearchConditionRequest.group("AND",
                Condition.of("$.id", "EQUALS", id));
        CompletableFuture<ArrayNode> itemsFuture = entityService.getItemsByCondition("PetJob", ENTITY_VERSION, condition);
        ArrayNode items = itemsFuture.get();
        if (items.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("PetJob not found");
        }
        ObjectNode obj = (ObjectNode) items.get(0);
        PetJob petJob = entityService.convertObjectNode(obj, PetJob.class);
        return ResponseEntity.ok(petJob);
    }

    // Pet endpoints

    @PostMapping("/pets")
    public ResponseEntity<?> createPet(@RequestBody Pet pet) throws Exception {
        if (pet == null || pet.getName() == null || pet.getName().isBlank()
                || pet.getSpecies() == null || pet.getSpecies().isBlank()) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("Required pet fields missing");
        }
        pet.setPetId(UUID.randomUUID().toString());
        pet.setStatus("NEW");

        CompletableFuture<UUID> idFuture = entityService.addItem("Pet", ENTITY_VERSION, pet);
        UUID technicalId = idFuture.get();
        pet.setTechnicalId(technicalId);

        return ResponseEntity.status(HttpStatus.CREATED).body(pet);
    }

    @GetMapping("/pets/{id}")
    public ResponseEntity<?> getPet(@PathVariable String id) throws Exception {
        SearchConditionRequest condition = SearchConditionRequest.group("AND",
                Condition.of("$.id", "EQUALS", id));
        CompletableFuture<ArrayNode> itemsFuture = entityService.getItemsByCondition("Pet", ENTITY_VERSION, condition);
        ArrayNode items = itemsFuture.get();
        if (items.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Pet not found");
        }
        ObjectNode obj = (ObjectNode) items.get(0);
        Pet pet = entityService.convertObjectNode(obj, Pet.class);
        return ResponseEntity.ok(pet);
    }

    // AdoptionRequest endpoints

    @PostMapping("/adoptionRequests")
    public ResponseEntity<?> createAdoptionRequest(@RequestBody AdoptionRequest request) throws Exception {
        if (request == null || request.getPetId() == null || request.getPetId().isBlank()
                || request.getRequesterName() == null || request.getRequesterName().isBlank()) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("Required adoption request fields missing");
        }
        // Check pet availability by petId with status NEW or AVAILABLE
        Condition condPetId = Condition.of("$.petId", "EQUALS", request.getPetId());
        Condition condStatusNew = Condition.of("$.status", "EQUALS", "NEW");
        Condition condStatusAvailable = Condition.of("$.status", "EQUALS", "AVAILABLE");
        SearchConditionRequest condStatusNewOrAvailable = SearchConditionRequest.group("OR", condStatusNew, condStatusAvailable);
        SearchConditionRequest condition = SearchConditionRequest.group("AND", condPetId, condStatusNewOrAvailable);

        CompletableFuture<ArrayNode> petsFuture = entityService.getItemsByCondition("Pet", ENTITY_VERSION, condition);
        ArrayNode pets = petsFuture.get();

        if (pets.isEmpty()) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("Pet not available for adoption");
        }

        request.setRequestId(UUID.randomUUID().toString());
        request.setRequestDate(LocalDateTime.now());
        request.setStatus("PENDING");

        CompletableFuture<UUID> idFuture = entityService.addItem("AdoptionRequest", ENTITY_VERSION, request);
        UUID technicalId = idFuture.get();
        request.setTechnicalId(technicalId);

        return ResponseEntity.status(HttpStatus.CREATED).body(request);
    }

    @GetMapping("/adoptionRequests/{id}")
    public ResponseEntity<?> getAdoptionRequest(@PathVariable String id) throws Exception {
        SearchConditionRequest condition = SearchConditionRequest.group("AND",
                Condition.of("$.id", "EQUALS", id));
        CompletableFuture<ArrayNode> itemsFuture = entityService.getItemsByCondition("AdoptionRequest", ENTITY_VERSION, condition);
        ArrayNode items = itemsFuture.get();
        if (items.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("AdoptionRequest not found");
        }
        ObjectNode obj = (ObjectNode) items.get(0);
        AdoptionRequest adoptionRequest = entityService.convertObjectNode(obj, AdoptionRequest.class);
        return ResponseEntity.ok(adoptionRequest);
    }
}