package com.java_template.application.controller;

import static com.java_template.common.config.Config.*;

import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.java_template.common.service.EntityService;
import com.java_template.application.entity.userimportjob.version_1.UserImportJob;
import com.java_template.application.entity.user.version_1.User;
import com.java_template.application.entity.cart.version_1.Cart;
import com.java_template.application.entity.cartitem.version_1.CartItem;
import com.java_template.application.entity.order.version_1.Order;
import com.java_template.application.entity.orderitem.version_1.OrderItem;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.http.ResponseEntity;
import org.springframework.http.HttpStatus;

import lombok.Data;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.NoSuchElementException;

@RestController
@RequestMapping("/api")
@Tag(name = "Order Management Controller", description = "Controller for handling event-driven API endpoints for Users, UserImportJobs, Carts, and Orders")
public class Controller {

    private static final Logger logger = LoggerFactory.getLogger(Controller.class);

    private final EntityService entityService;

    public Controller(EntityService entityService) {
        this.entityService = entityService;
    }

    // --- UserImportJob ---

    @Operation(summary = "Create UserImportJob to import users", description = "Create UserImportJob entity which triggers user import event")
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "UserImportJob created", content = @Content(schema = @Schema(implementation = TechnicalIdResponse.class))),
        @ApiResponse(responseCode = "400", description = "Invalid request"),
        @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @PostMapping("/admin/users/import")
    public ResponseEntity<?> createUserImportJob(@RequestBody UserImportJobCreateRequest request) {
        try {
            UserImportJob userImportJob = new UserImportJob();
            // jobId is generated by the system, not in request, so not set here
            userImportJob.setImportData(request.getImportData());
            userImportJob.setStatus("PENDING");
            userImportJob.setCreatedAt(java.time.LocalDateTime.now());

            CompletableFuture<UUID> idFuture = entityService.addItem(
                UserImportJob.ENTITY_NAME,
                String.valueOf(UserImportJob.ENTITY_VERSION),
                userImportJob
            );
            UUID technicalId = idFuture.get();
            return ResponseEntity.ok(new TechnicalIdResponse(technicalId.toString()));
        } catch (IllegalArgumentException e) {
            logger.error("Invalid createUserImportJob request", e);
            return ResponseEntity.badRequest().body(e.getMessage());
        } catch (ExecutionException e) {
            Throwable cause = e.getCause();
            if (cause instanceof NoSuchElementException) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(cause.getMessage());
            } else if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            } else {
                logger.error("Execution error in createUserImportJob", e);
                return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(cause.getMessage());
            }
        } catch (Exception e) {
            logger.error("Unexpected error in createUserImportJob", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    @Operation(summary = "Get UserImportJob status by jobId", description = "Retrieve full UserImportJob entity data by jobId")
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "UserImportJob found", content = @Content(schema = @Schema(implementation = UserImportJob.class))),
        @ApiResponse(responseCode = "400", description = "Invalid jobId"),
        @ApiResponse(responseCode = "404", description = "UserImportJob not found"),
        @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @GetMapping("/admin/users/import/{technicalId}")
    public ResponseEntity<?> getUserImportJobById(
        @Parameter(name = "technicalId", description = "Technical ID of the UserImportJob")
        @PathVariable("technicalId") String technicalIdStr) {
        try {
            UUID technicalId = UUID.fromString(technicalIdStr);
            CompletableFuture<ObjectNode> itemFuture = entityService.getItem(
                UserImportJob.ENTITY_NAME,
                String.valueOf(UserImportJob.ENTITY_VERSION),
                technicalId
            );
            ObjectNode item = itemFuture.get();
            if (item == null) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body("UserImportJob not found");
            }
            return ResponseEntity.ok(item);
        } catch (IllegalArgumentException e) {
            logger.error("Invalid getUserImportJobById request", e);
            return ResponseEntity.badRequest().body(e.getMessage());
        } catch (ExecutionException e) {
            Throwable cause = e.getCause();
            if (cause instanceof NoSuchElementException) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(cause.getMessage());
            } else if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            } else {
                logger.error("Execution error in getUserImportJobById", e);
                return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(cause.getMessage());
            }
        } catch (Exception e) {
            logger.error("Unexpected error in getUserImportJobById", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    // --- User ---

    @Operation(summary = "Get User by userId", description = "Retrieve full User entity data by userId")
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "User found", content = @Content(schema = @Schema(implementation = User.class))),
        @ApiResponse(responseCode = "400", description = "Invalid userId"),
        @ApiResponse(responseCode = "404", description = "User not found"),
        @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @GetMapping("/users/{technicalId}")
    public ResponseEntity<?> getUserById(
        @Parameter(name = "technicalId", description = "Technical ID of the User")
        @PathVariable("technicalId") String technicalIdStr) {
        try {
            UUID technicalId = UUID.fromString(technicalIdStr);
            CompletableFuture<ObjectNode> itemFuture = entityService.getItem(
                User.ENTITY_NAME,
                String.valueOf(User.ENTITY_VERSION),
                technicalId
            );
            ObjectNode item = itemFuture.get();
            if (item == null) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body("User not found");
            }
            return ResponseEntity.ok(item);
        } catch (IllegalArgumentException e) {
            logger.error("Invalid getUserById request", e);
            return ResponseEntity.badRequest().body(e.getMessage());
        } catch (ExecutionException e) {
            Throwable cause = e.getCause();
            if (cause instanceof NoSuchElementException) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(cause.getMessage());
            } else if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            } else {
                logger.error("Execution error in getUserById", e);
                return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(cause.getMessage());
            }
        } catch (Exception e) {
            logger.error("Unexpected error in getUserById", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    // --- Cart ---

    @Operation(summary = "Create or update Cart for customer", description = "Create or update Cart entity for a customer which triggers Cart processing")
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "Cart created or updated", content = @Content(schema = @Schema(implementation = TechnicalIdResponse.class))),
        @ApiResponse(responseCode = "400", description = "Invalid request"),
        @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @PostMapping("/customers/{customerId}/cart")
    public ResponseEntity<?> createOrUpdateCart(
        @Parameter(name = "customerId", description = "Customer ID for the Cart")
        @PathVariable("customerId") String customerId,
        @RequestBody CartCreateOrUpdateRequest request) {
        try {
            Cart cart = new Cart();
            cart.setCartId(null); // We do not have cartId in path or request, so let workflow or DB generate or require it in a real scenario
            cart.setCustomerId(customerId);
            cart.setItems(request.getItems());
            cart.setStatus("ACTIVE");
            cart.setCreatedAt(java.time.LocalDateTime.now());

            CompletableFuture<UUID> idFuture = entityService.addItem(
                Cart.ENTITY_NAME,
                String.valueOf(Cart.ENTITY_VERSION),
                cart
            );
            UUID technicalId = idFuture.get();
            return ResponseEntity.ok(new TechnicalIdResponse(technicalId.toString()));
        } catch (IllegalArgumentException e) {
            logger.error("Invalid createOrUpdateCart request", e);
            return ResponseEntity.badRequest().body(e.getMessage());
        } catch (ExecutionException e) {
            Throwable cause = e.getCause();
            if (cause instanceof NoSuchElementException) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(cause.getMessage());
            } else if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            } else {
                logger.error("Execution error in createOrUpdateCart", e);
                return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(cause.getMessage());
            }
        } catch (Exception e) {
            logger.error("Unexpected error in createOrUpdateCart", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    @Operation(summary = "Retrieve current Cart for customer", description = "Retrieve full Cart entity data for a customer")
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "Cart found", content = @Content(schema = @Schema(implementation = Cart.class))),
        @ApiResponse(responseCode = "400", description = "Invalid customerId"),
        @ApiResponse(responseCode = "404", description = "Cart not found"),
        @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @GetMapping("/customers/{customerId}/cart")
    public ResponseEntity<?> getCartByCustomerId(
        @Parameter(name = "customerId", description = "Customer ID for the Cart")
        @PathVariable("customerId") String customerId) {
        try {
            // We do not have technicalId for cart from path, so we assume customerId is unique key for cart retrieval
            // Using getItemsByCondition with customerId filter
            com.java_template.common.util.SearchConditionRequest condition = com.java_template.common.util.SearchConditionRequest.group("AND",
                com.java_template.common.util.Condition.of("$.customerId", "EQUALS", customerId)
            );
            CompletableFuture<ArrayNode> itemsFuture = entityService.getItemsByCondition(
                Cart.ENTITY_NAME,
                String.valueOf(Cart.ENTITY_VERSION),
                condition,
                true
            );
            ArrayNode items = itemsFuture.get();
            if (items == null || items.isEmpty()) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Cart not found for customer");
            }
            // Return the first found cart for the customer
            return ResponseEntity.ok(items.get(0));
        } catch (IllegalArgumentException e) {
            logger.error("Invalid getCartByCustomerId request", e);
            return ResponseEntity.badRequest().body(e.getMessage());
        } catch (ExecutionException e) {
            Throwable cause = e.getCause();
            if (cause instanceof NoSuchElementException) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(cause.getMessage());
            } else if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            } else {
                logger.error("Execution error in getCartByCustomerId", e);
                return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(cause.getMessage());
            }
        } catch (Exception e) {
            logger.error("Unexpected error in getCartByCustomerId", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    // --- Order ---

    @Operation(summary = "Create Order (checkout)", description = "Create Order entity which triggers Order processing")
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "Order created", content = @Content(schema = @Schema(implementation = TechnicalIdResponse.class))),
        @ApiResponse(responseCode = "400", description = "Invalid request"),
        @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @PostMapping("/customers/{customerId}/orders")
    public ResponseEntity<?> createOrder(
        @Parameter(name = "customerId", description = "Customer ID for the Order")
        @PathVariable("customerId") String customerId,
        @RequestBody OrderCreateRequest request) {
        try {
            Order order = new Order();
            // orderId is generated by the system, not in request, so not set here
            order.setCustomerId(customerId);
            // We don't have items in request, only cartId, so items might be populated in workflow
            order.setItems(null);
            order.setStatus("PENDING");
            order.setCreatedAt(java.time.LocalDateTime.now());

            // We might want to store cartId in some way, but entity Order does not have cartId field
            // So we keep it out of order entity, as per entity definition

            CompletableFuture<UUID> idFuture = entityService.addItem(
                Order.ENTITY_NAME,
                String.valueOf(Order.ENTITY_VERSION),
                order
            );
            UUID technicalId = idFuture.get();
            return ResponseEntity.ok(new TechnicalIdResponse(technicalId.toString()));
        } catch (IllegalArgumentException e) {
            logger.error("Invalid createOrder request", e);
            return ResponseEntity.badRequest().body(e.getMessage());
        } catch (ExecutionException e) {
            Throwable cause = e.getCause();
            if (cause instanceof NoSuchElementException) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(cause.getMessage());
            } else if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            } else {
                logger.error("Execution error in createOrder", e);
                return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(cause.getMessage());
            }
        } catch (Exception e) {
            logger.error("Unexpected error in createOrder", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    @Operation(summary = "Get Order by orderId", description = "Retrieve full Order entity data by orderId")
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "Order found", content = @Content(schema = @Schema(implementation = Order.class))),
        @ApiResponse(responseCode = "400", description = "Invalid orderId"),
        @ApiResponse(responseCode = "404", description = "Order not found"),
        @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @GetMapping("/customers/{customerId}/orders/{technicalId}")
    public ResponseEntity<?> getOrderById(
        @Parameter(name = "technicalId", description = "Technical ID of the Order")
        @PathVariable("technicalId") String technicalIdStr) {
        try {
            UUID technicalId = UUID.fromString(technicalIdStr);
            CompletableFuture<ObjectNode> itemFuture = entityService.getItem(
                Order.ENTITY_NAME,
                String.valueOf(Order.ENTITY_VERSION),
                technicalId
            );
            ObjectNode item = itemFuture.get();
            if (item == null) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Order not found");
            }
            return ResponseEntity.ok(item);
        } catch (IllegalArgumentException e) {
            logger.error("Invalid getOrderById request", e);
            return ResponseEntity.badRequest().body(e.getMessage());
        } catch (ExecutionException e) {
            Throwable cause = e.getCause();
            if (cause instanceof NoSuchElementException) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(cause.getMessage());
            } else if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            } else {
                logger.error("Execution error in getOrderById", e);
                return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(cause.getMessage());
            }
        } catch (Exception e) {
            logger.error("Unexpected error in getOrderById", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    @Data
    public static class TechnicalIdResponse {
        @Schema(description = "Technical ID of the entity", example = "123e4567-e89b-12d3-a456-426614174000")
        private final String technicalId;
    }

    @Data
    public static class UserImportJobCreateRequest {
        @Schema(description = "Raw user data in JSON or CSV format", example = "[{\"name\":\"Alice\", \"email\":\"alice@example.com\", \"role\":\"Admin\"}]")
        private String importData;
    }

    @Data
    public static class CartCreateOrUpdateRequest {
        @Schema(description = "List of current products in cart")
        private java.util.List<CartItem> items;
    }

    @Data
    public static class OrderCreateRequest {
        @Schema(description = "Cart ID for checkout", example = "cart-789")
        private String cartId;
    }
}