package com.java_template.entity;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.scheduling.annotation.Async;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.server.ResponseStatusException;

import java.net.URI;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

@RestController
@RequestMapping("/api")
@Validated
public class EntityControllerPrototype {

    private static final Logger logger = LoggerFactory.getLogger(EntityControllerPrototype.class);

    private final Map<UUID, Subscriber> subscribers = new ConcurrentHashMap<>();
    private final Map<UUID, List<Interaction>> interactions = new ConcurrentHashMap<>();
    private final List<SentFact> sentFacts = Collections.synchronizedList(new ArrayList<>());

    private final RestTemplate restTemplate = new RestTemplate();
    private final ObjectMapper objectMapper = new ObjectMapper();

    private static final String CAT_FACT_API_URL = "https://catfact.ninja/fact";

    // Models

    static class Subscriber {
        private UUID subscriberId;
        private String email;
        private String status;
        // getters/setters generated by Lombok in real code
    }

    @Data
    static class SignUpRequest {
        @NotBlank
        @Email
        private String email;
    }

    @Data
    static class InteractionRequest {
        @NotBlank
        @Pattern(regexp = "^[0-9a-fA-F\\-]{36}$")
        private String subscriberId;

        @NotBlank
        @Pattern(regexp = "open|click")
        private String interactionType;

        @NotBlank
        private String timestamp; // ISO-8601 string
    }

    @Data
    static class SentFact {
        private String fact;
        private Instant timestamp;
        private int sentCount;
    }

    @Data
    static class Interaction {
        private UUID subscriberId;
        private String interactionType;
        private Instant timestamp;
    }

    // Endpoints

    @PostMapping("/subscribers")
    public Subscriber signUp(@RequestBody @Valid SignUpRequest request) {
        logger.info("Received sign-up: {}", request.getEmail());
        boolean exists = subscribers.values().stream()
                .anyMatch(s -> s.getEmail().equalsIgnoreCase(request.getEmail()));
        if (exists) {
            throw new ResponseStatusException(HttpStatus.CONFLICT, "Email already subscribed");
        }
        Subscriber sub = new Subscriber();
        sub.setSubscriberId(UUID.randomUUID());
        sub.setEmail(request.getEmail());
        sub.setStatus("subscribed");
        subscribers.put(sub.getSubscriberId(), sub);
        logger.info("Subscriber created: {}", sub.getSubscriberId());
        return sub;
    }

    @PostMapping("/facts/sendWeekly")
    public Map<String, Object> sendWeeklyFact() {
        logger.info("Triggering weekly send");
        String factText;
        try {
            String resp = restTemplate.getForObject(new URI(CAT_FACT_API_URL), String.class);
            JsonNode root = objectMapper.readTree(resp);
            factText = root.path("fact").asText();
        } catch (Exception e) {
            logger.error("Fetch failed", e);
            throw new ResponseStatusException(HttpStatus.BAD_GATEWAY, "Failed to fetch cat fact");
        }
        int count = subscribers.size();
        CompletableFuture.runAsync(() -> {
            logger.info("Sending to {} subs", count);
            // TODO: implement real email logic
            sentFacts.add(new SentFact(factText, Instant.now(), count));
        });
        Map<String, Object> out = new HashMap<>();
        out.put("sentCount", count);
        out.put("catFact", factText);
        out.put("timestamp", Instant.now().toString());
        return out;
    }

    @GetMapping("/subscribers")
    public Collection<Subscriber> getSubscribers() {
        return subscribers.values();
    }

    @GetMapping("/reports/summary")
    public Map<String, Object> getReportSummary() {
        int totalSubs = subscribers.size();
        int totalSent = sentFacts.size();
        long opens = interactions.values().stream().flatMap(List::stream)
                .filter(i -> "open".equals(i.getInteractionType())).count();
        long clicks = interactions.values().stream().flatMap(List::stream)
                .filter(i -> "click".equals(i.getInteractionType())).count();
        Instant last = sentFacts.stream().map(SentFact::getTimestamp)
                .max(Instant::compareTo).orElse(null);

        Map<String, Object> summary = new HashMap<>();
        summary.put("totalSubscribers", totalSubs);
        summary.put("totalFactsSent", totalSent);
        summary.put("totalEmailOpens", opens);
        summary.put("totalEmailClicks", clicks);
        summary.put("lastFactSentAt", last != null ? last.toString() : null);
        return summary;
    }

    @PostMapping("/interactions")
    public Map<String, Object> trackInteraction(@RequestBody @Valid InteractionRequest request) {
        UUID sid;
        try {
            sid = UUID.fromString(request.getSubscriberId());
        } catch (IllegalArgumentException e) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid UUID");
        }
        if (!subscribers.containsKey(sid)) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Subscriber not found");
        }
        Instant ts;
        try {
            ts = Instant.parse(request.getTimestamp());
        } catch (Exception e) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid timestamp");
        }
        Interaction inter = new Interaction(sid, request.getInteractionType(), ts);
        interactions.computeIfAbsent(sid, k -> Collections.synchronizedList(new ArrayList<>()))
                .add(inter);

        Map<String, Object> resp = new HashMap<>();
        resp.put("status", "recorded");
        resp.put("subscriberId", sid);
        resp.put("interactionType", request.getInteractionType());
        resp.put("timestamp", ts.toString());
        return resp;
    }

    @ExceptionHandler(ResponseStatusException.class)
    @ResponseStatus
    public Map<String, Object> handleStatus(ResponseStatusException ex) {
        Map<String, Object> err = new HashMap<>();
        err.put("status", ex.getStatusCode().value());
        err.put("error", ex.getStatusCode().getReasonPhrase());
        err.put("message", ex.getReason());
        return err;
    }

    @ExceptionHandler(Exception.class)
    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
    public Map<String, Object> handleAll(Exception ex) {
        Map<String, Object> err = new HashMap<>();
        err.put("status", 500);
        err.put("error", "Internal Server Error");
        err.put("message", "Unexpected error");
        return err;
    }
}