package com.java_template.application.controller.laureate.version_1;

import static com.java_template.common.config.Config.*;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.java_template.application.entity.laureate.version_1.Laureate;
import com.java_template.common.service.EntityService;
import com.java_template.common.util.Condition;
import com.java_template.common.util.SearchConditionRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import lombok.Data;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.UUID;
import java.util.concurrent.ExecutionException;

@RestController
@RequestMapping("/api/v1/laureates")
@Tag(name = "Laureate", description = "Operations for Laureate entity")
public class LaureateController {

    private static final Logger logger = LoggerFactory.getLogger(LaureateController.class);

    private final EntityService entityService;
    private final ObjectMapper mapper = new ObjectMapper();

    public LaureateController(EntityService entityService) {
        this.entityService = entityService;
    }

    @Operation(summary = "Create a Laureate", description = "Persist a single Laureate. Returns the technicalId generated by the datastore.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(schema = @Schema(implementation = CreateLaureateResponse.class))),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = @Content),
            @ApiResponse(responseCode = "500", description = "Internal Error", content = @Content)
    })
    @PostMapping
    public ResponseEntity<?> createLaureate(
            @io.swagger.v3.oas.annotations.parameters.RequestBody(description = "Laureate to create", required = true, content = @Content(schema = @Schema(implementation = CreateLaureateRequest.class)))
            @RequestBody CreateLaureateRequest request) {
        try {
            if (request == null) throw new IllegalArgumentException("Request body is required");
            Laureate l = toEntity(request);
            UUID id = entityService.addItem(
                    Laureate.ENTITY_NAME,
                    String.valueOf(Laureate.ENTITY_VERSION),
                    l
            ).get();
            CreateLaureateResponse resp = new CreateLaureateResponse(id.toString());
            return ResponseEntity.ok(resp);
        } catch (IllegalArgumentException iae) {
            logger.warn("Invalid request: {}", iae.getMessage(), iae);
            return ResponseEntity.badRequest().body(iae.getMessage());
        } catch (ExecutionException ee) {
            Throwable cause = ee.getCause();
            if (cause instanceof NoSuchElementException) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(cause.getMessage());
            }
            if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            }
            logger.error("ExecutionException creating Laureate", ee);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ee.getMessage());
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
            logger.error("Interrupted while creating Laureate", ie);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ie.getMessage());
        } catch (Exception e) {
            logger.error("Error creating Laureate", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    @Operation(summary = "Create multiple Laureates", description = "Persist multiple Laureates in a batch. Returns list of technicalIds.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(schema = @Schema(implementation = BatchCreateLaureateResponse.class))),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = @Content),
            @ApiResponse(responseCode = "500", description = "Internal Error", content = @Content)
    })
    @PostMapping("/batch")
    public ResponseEntity<?> createLaureatesBatch(
            @io.swagger.v3.oas.annotations.parameters.RequestBody(description = "List of Laureates to create", required = true, content = @Content(array = @ArraySchema(schema = @Schema(implementation = CreateLaureateRequest.class))))
            @RequestBody List<CreateLaureateRequest> requests) {
        try {
            if (requests == null || requests.isEmpty()) throw new IllegalArgumentException("Request body must contain at least one laureate");
            List<Laureate> entities = new ArrayList<>();
            for (CreateLaureateRequest r : requests) entities.add(toEntity(r));
            List<java.util.UUID> ids = entityService.addItems(
                    Laureate.ENTITY_NAME,
                    String.valueOf(Laureate.ENTITY_VERSION),
                    entities
            ).get();
            List<String> technicalIds = new ArrayList<>();
            for (UUID u : ids) technicalIds.add(u.toString());
            BatchCreateLaureateResponse resp = new BatchCreateLaureateResponse(technicalIds);
            return ResponseEntity.ok(resp);
        } catch (IllegalArgumentException iae) {
            logger.warn("Invalid batch request: {}", iae.getMessage(), iae);
            return ResponseEntity.badRequest().body(iae.getMessage());
        } catch (ExecutionException ee) {
            Throwable cause = ee.getCause();
            if (cause instanceof NoSuchElementException) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(cause.getMessage());
            }
            if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            }
            logger.error("ExecutionException in batch create Laureates", ee);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ee.getMessage());
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
            logger.error("Interrupted while batch creating Laureates", ie);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ie.getMessage());
        } catch (Exception e) {
            logger.error("Error batch creating Laureates", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    @Operation(summary = "Get a Laureate by technicalId", description = "Retrieve a Laureate by its datastore technicalId")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(schema = @Schema(implementation = LaureateResponse.class))),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = @Content),
            @ApiResponse(responseCode = "404", description = "Not Found", content = @Content),
            @ApiResponse(responseCode = "500", description = "Internal Error", content = @Content)
    })
    @GetMapping("/{technicalId}")
    public ResponseEntity<?> getLaureate(
            @Parameter(name = "technicalId", description = "Technical ID of the entity", required = true)
            @PathVariable("technicalId") String technicalId) {
        try {
            UUID tid = UUID.fromString(technicalId);
            ObjectNode node = entityService.getItem(
                    Laureate.ENTITY_NAME,
                    String.valueOf(Laureate.ENTITY_VERSION),
                    tid
            ).get();
            Laureate entity = mapper.treeToValue(node, Laureate.class);
            LaureateResponse resp = fromEntity(entity);
            resp.setTechnicalId(technicalId);
            return ResponseEntity.ok(resp);
        } catch (IllegalArgumentException iae) {
            logger.warn("Invalid technicalId or request: {}", iae.getMessage(), iae);
            return ResponseEntity.badRequest().body(iae.getMessage());
        } catch (ExecutionException ee) {
            Throwable cause = ee.getCause();
            if (cause instanceof NoSuchElementException) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(cause.getMessage());
            }
            if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            }
            logger.error("ExecutionException getting Laureate", ee);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ee.getMessage());
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
            logger.error("Interrupted while getting Laureate", ie);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ie.getMessage());
        } catch (JsonProcessingException jpe) {
            logger.error("Error mapping Laureate JSON", jpe);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(jpe.getMessage());
        } catch (Exception e) {
            logger.error("Error getting Laureate", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    @Operation(summary = "Get all Laureates", description = "Retrieve all Laureates")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(array = @ArraySchema(schema = @Schema(implementation = LaureateResponse.class)))),
            @ApiResponse(responseCode = "500", description = "Internal Error", content = @Content)
    })
    @GetMapping
    public ResponseEntity<?> getAllLaureates() {
        try {
            ArrayNode nodes = entityService.getItems(
                    Laureate.ENTITY_NAME,
                    String.valueOf(Laureate.ENTITY_VERSION)
            ).get();
            List<LaureateResponse> result = new ArrayList<>();
            for (int i = 0; i < nodes.size(); i++) {
                ObjectNode node = (ObjectNode) nodes.get(i);
                Laureate entity = mapper.treeToValue(node, Laureate.class);
                LaureateResponse resp = fromEntity(entity);
                result.add(resp);
            }
            return ResponseEntity.ok(result);
        } catch (ExecutionException ee) {
            Throwable cause = ee.getCause();
            if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            }
            logger.error("ExecutionException getting all Laureates", ee);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ee.getMessage());
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
            logger.error("Interrupted while getting all Laureates", ie);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ie.getMessage());
        } catch (JsonProcessingException jpe) {
            logger.error("Error mapping Laureate JSON list", jpe);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(jpe.getMessage());
        } catch (Exception e) {
            logger.error("Error getting all Laureates", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    @Operation(summary = "Search Laureates by simple condition", description = "Search by a single field condition. Query parameters: field, operator, value")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(array = @ArraySchema(schema = @Schema(implementation = LaureateResponse.class)))),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = @Content),
            @ApiResponse(responseCode = "500", description = "Internal Error", content = @Content)
    })
    @GetMapping("/search")
    public ResponseEntity<?> searchLaureates(
            @RequestParam("field") String field,
            @RequestParam("operator") String operator,
            @RequestParam("value") String value
    ) {
        try {
            if (field == null || field.isBlank() || operator == null || operator.isBlank()) {
                throw new IllegalArgumentException("field and operator are required");
            }
            Condition condition = Condition.of("$.%s".formatted(field), operator, value);
            SearchConditionRequest cond = SearchConditionRequest.group("AND", condition);
            ArrayNode nodes = entityService.getItemsByCondition(
                    Laureate.ENTITY_NAME,
                    String.valueOf(Laureate.ENTITY_VERSION),
                    cond,
                    true
            ).get();
            List<LaureateResponse> result = new ArrayList<>();
            for (int i = 0; i < nodes.size(); i++) {
                ObjectNode node = (ObjectNode) nodes.get(i);
                Laureate entity = mapper.treeToValue(node, Laureate.class);
                LaureateResponse resp = fromEntity(entity);
                result.add(resp);
            }
            return ResponseEntity.ok(result);
        } catch (IllegalArgumentException iae) {
            logger.warn("Invalid search request: {}", iae.getMessage(), iae);
            return ResponseEntity.badRequest().body(iae.getMessage());
        } catch (ExecutionException ee) {
            Throwable cause = ee.getCause();
            if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            }
            logger.error("ExecutionException searching Laureates", ee);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ee.getMessage());
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
            logger.error("Interrupted while searching Laureates", ie);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ie.getMessage());
        } catch (JsonProcessingException jpe) {
            logger.error("Error mapping Laureate search results", jpe);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(jpe.getMessage());
        } catch (Exception e) {
            logger.error("Error searching Laureates", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    @Operation(summary = "Update a Laureate", description = "Update Laureate by technicalId")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(schema = @Schema(implementation = UpdateLaureateResponse.class))),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = @Content),
            @ApiResponse(responseCode = "404", description = "Not Found", content = @Content),
            @ApiResponse(responseCode = "500", description = "Internal Error", content = @Content)
    })
    @PutMapping("/{technicalId}")
    public ResponseEntity<?> updateLaureate(
            @Parameter(name = "technicalId", description = "Technical ID of the entity", required = true)
            @PathVariable("technicalId") String technicalId,
            @io.swagger.v3.oas.annotations.parameters.RequestBody(description = "Laureate payload to update", required = true, content = @Content(schema = @Schema(implementation = UpdateLaureateRequest.class)))
            @RequestBody UpdateLaureateRequest request) {
        try {
            if (request == null) throw new IllegalArgumentException("Request body is required");
            UUID tid = UUID.fromString(technicalId);
            Laureate l = toEntity(request);
            UUID updated = entityService.updateItem(
                    Laureate.ENTITY_NAME,
                    String.valueOf(Laureate.ENTITY_VERSION),
                    tid,
                    l
            ).get();
            UpdateLaureateResponse resp = new UpdateLaureateResponse(updated.toString());
            return ResponseEntity.ok(resp);
        } catch (IllegalArgumentException iae) {
            logger.warn("Invalid update request: {}", iae.getMessage(), iae);
            return ResponseEntity.badRequest().body(iae.getMessage());
        } catch (ExecutionException ee) {
            Throwable cause = ee.getCause();
            if (cause instanceof NoSuchElementException) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(cause.getMessage());
            }
            if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            }
            logger.error("ExecutionException updating Laureate", ee);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ee.getMessage());
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
            logger.error("Interrupted while updating Laureate", ie);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ie.getMessage());
        } catch (Exception e) {
            logger.error("Error updating Laureate", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    @Operation(summary = "Delete a Laureate", description = "Delete Laureate by technicalId")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(schema = @Schema(implementation = DeleteLaureateResponse.class))),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = @Content),
            @ApiResponse(responseCode = "404", description = "Not Found", content = @Content),
            @ApiResponse(responseCode = "500", description = "Internal Error", content = @Content)
    })
    @DeleteMapping("/{technicalId}")
    public ResponseEntity<?> deleteLaureate(
            @Parameter(name = "technicalId", description = "Technical ID of the entity", required = true)
            @PathVariable("technicalId") String technicalId) {
        try {
            UUID tid = UUID.fromString(technicalId);
            UUID deleted = entityService.deleteItem(
                    Laureate.ENTITY_NAME,
                    String.valueOf(Laureate.ENTITY_VERSION),
                    tid
            ).get();
            DeleteLaureateResponse resp = new DeleteLaureateResponse(deleted.toString());
            return ResponseEntity.ok(resp);
        } catch (IllegalArgumentException iae) {
            logger.warn("Invalid technicalId for delete: {}", iae.getMessage(), iae);
            return ResponseEntity.badRequest().body(iae.getMessage());
        } catch (ExecutionException ee) {
            Throwable cause = ee.getCause();
            if (cause instanceof NoSuchElementException) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(cause.getMessage());
            }
            if (cause instanceof IllegalArgumentException) {
                return ResponseEntity.badRequest().body(cause.getMessage());
            }
            logger.error("ExecutionException deleting Laureate", ee);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ee.getMessage());
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
            logger.error("Interrupted while deleting Laureate", ie);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ie.getMessage());
        } catch (Exception e) {
            logger.error("Error deleting Laureate", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
        }
    }

    // Helpers to convert between DTOs and entity

    private Laureate toEntity(CreateLaureateRequest req) {
        Laureate l = new Laureate();
        l.setId(req.getId());
        l.setSourceRecordId(req.getSourceRecordId());
        l.setFullName(req.getFullName());
        l.setBirthDate(req.getBirthDate());
        l.setDiedDate(req.getDiedDate());
        l.setBirthCity(req.getBirthCity());
        l.setBirthCountry(req.getBirthCountry());
        l.setCategory(req.getCategory());
        l.setYear(req.getYear());
        l.setMotivation(req.getMotivation());
        l.setStatus(req.getStatus());
        l.setCreatedAt(req.getCreatedAt());
        return l;
    }

    private Laureate toEntity(UpdateLaureateRequest req) {
        Laureate l = new Laureate();
        l.setId(req.getId());
        l.setSourceRecordId(req.getSourceRecordId());
        l.setFullName(req.getFullName());
        l.setBirthDate(req.getBirthDate());
        l.setDiedDate(req.getDiedDate());
        l.setBirthCity(req.getBirthCity());
        l.setBirthCountry(req.getBirthCountry());
        l.setCategory(req.getCategory());
        l.setYear(req.getYear());
        l.setMotivation(req.getMotivation());
        l.setStatus(req.getStatus());
        l.setCreatedAt(req.getCreatedAt());
        return l;
    }

    private LaureateResponse fromEntity(Laureate entity) {
        LaureateResponse r = new LaureateResponse();
        r.setId(entity.getId());
        r.setSourceRecordId(entity.getSourceRecordId());
        r.setFullName(entity.getFullName());
        r.setBirthDate(entity.getBirthDate());
        r.setDiedDate(entity.getDiedDate());
        r.setBirthCity(entity.getBirthCity());
        r.setBirthCountry(entity.getBirthCountry());
        r.setCategory(entity.getCategory());
        r.setYear(entity.getYear());
        r.setMotivation(entity.getMotivation());
        r.setStatus(entity.getStatus());
        r.setCreatedAt(entity.getCreatedAt());
        return r;
    }

    // DTOs

    @Data
    @Schema(name = "CreateLaureateRequest", description = "Payload to create a Laureate")
    public static class CreateLaureateRequest {
        @Schema(description = "Domain id from source or generated", example = "rec-abc123")
        private String id;
        @Schema(description = "Original source identifier", example = "src-1")
        private String sourceRecordId;
        @Schema(description = "Full name of the laureate", example = "Marie Curie")
        private String fullName;
        @Schema(description = "Birth date (ISO or partial)", example = "1867-11-07")
        private String birthDate;
        @Schema(description = "Died date", example = "1934-07-04")
        private String diedDate;
        @Schema(description = "Birth city", example = "Warsaw")
        private String birthCity;
        @Schema(description = "Birth country", example = "Poland")
        private String birthCountry;
        @Schema(description = "Prize category", example = "chemistry")
        private String category;
        @Schema(description = "Prize year", example = "1911")
        private String year;
        @Schema(description = "Motivation text", example = "in recognition of...")
        private String motivation;
        @Schema(description = "Status", example = "RAW")
        private String status;
        @Schema(description = "Created at timestamp (ISO8601)", example = "2025-08-26T12:00:00Z")
        private String createdAt;
    }

    @Data
    @Schema(name = "BatchCreateLaureateResponse", description = "Response for batch create")
    public static class BatchCreateLaureateResponse {
        private List<String> technicalIds;
        public BatchCreateLaureateResponse() {}
        public BatchCreateLaureateResponse(List<String> technicalIds) { this.technicalIds = technicalIds; }
    }

    @Data
    @Schema(name = "CreateLaureateResponse", description = "Response when creating a Laureate")
    public static class CreateLaureateResponse {
        private String technicalId;
        public CreateLaureateResponse() {}
        public CreateLaureateResponse(String technicalId) { this.technicalId = technicalId; }
    }

    @Data
    @Schema(name = "LaureateResponse", description = "Laureate read response")
    public static class LaureateResponse {
        @Schema(description = "Datastore technical id")
        private String technicalId;
        @Schema(description = "Domain id from source or generated")
        private String id;
        @Schema(description = "Original source identifier")
        private String sourceRecordId;
        @Schema(description = "Full name of the laureate")
        private String fullName;
        @Schema(description = "Birth date (ISO or partial)")
        private String birthDate;
        @Schema(description = "Died date")
        private String diedDate;
        @Schema(description = "Birth city")
        private String birthCity;
        @Schema(description = "Birth country")
        private String birthCountry;
        @Schema(description = "Prize category")
        private String category;
        @Schema(description = "Prize year")
        private String year;
        @Schema(description = "Motivation text")
        private String motivation;
        @Schema(description = "Status")
        private String status;
        @Schema(description = "Created at timestamp (ISO8601)")
        private String createdAt;
    }

    @Data
    @Schema(name = "UpdateLaureateRequest", description = "Payload to update a Laureate")
    public static class UpdateLaureateRequest {
        @Schema(description = "Domain id from source or generated", example = "rec-abc123")
        private String id;
        @Schema(description = "Original source identifier", example = "src-1")
        private String sourceRecordId;
        @Schema(description = "Full name of the laureate", example = "Marie Curie")
        private String fullName;
        @Schema(description = "Birth date (ISO or partial)", example = "1867-11-07")
        private String birthDate;
        @Schema(description = "Died date", example = "1934-07-04")
        private String diedDate;
        @Schema(description = "Birth city", example = "Warsaw")
        private String birthCity;
        @Schema(description = "Birth country", example = "Poland")
        private String birthCountry;
        @Schema(description = "Prize category", example = "chemistry")
        private String category;
        @Schema(description = "Prize year", example = "1911")
        private String year;
        @Schema(description = "Motivation text", example = "in recognition of...")
        private String motivation;
        @Schema(description = "Status", example = "RAW")
        private String status;
        @Schema(description = "Created at timestamp (ISO8601)", example = "2025-08-26T12:00:00Z")
        private String createdAt;
    }

    @Data
    @Schema(name = "UpdateLaureateResponse", description = "Response when updating a Laureate")
    public static class UpdateLaureateResponse {
        private String technicalId;
        public UpdateLaureateResponse() {}
        public UpdateLaureateResponse(String technicalId) { this.technicalId = technicalId; }
    }

    @Data
    @Schema(name = "DeleteLaureateResponse", description = "Response when deleting a Laureate")
    public static class DeleteLaureateResponse {
        private String technicalId;
        public DeleteLaureateResponse() {}
        public DeleteLaureateResponse(String technicalId) { this.technicalId = technicalId; }
    }
}