package com.java_template.application.processor;

import com.java_template.application.entity.report.version_1.Report;
import com.java_template.common.serializer.ProcessorSerializer;
import com.java_template.common.serializer.SerializerFactory;
import com.java_template.common.serializer.ErrorInfo;
import com.java_template.common.workflow.CyodaEventContext;
import com.java_template.common.workflow.CyodaProcessor;
import com.java_template.common.workflow.OperationSpecification;
import org.cyoda.cloud.api.event.processing.EntityProcessorCalculationRequest;
import org.cyoda.cloud.api.event.processing.EntityProcessorCalculationResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.cyoda.cloud.api.event.common.DataPayload;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.java_template.common.service.EntityService;
import org.springframework.stereotype.Component;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Component
public class ReportGenerationProcessor implements CyodaProcessor {

    private static final Logger logger = LoggerFactory.getLogger(ReportGenerationProcessor.class);
    private final String className = this.getClass().getSimpleName();
    private final ProcessorSerializer serializer;

    public ReportGenerationProcessor(SerializerFactory serializerFactory) {
        this.serializer = serializerFactory.getDefaultProcessorSerializer();
    }

    @Override
    public EntityProcessorCalculationResponse process(CyodaEventContext<EntityProcessorCalculationRequest> context) {
        EntityProcessorCalculationRequest request = context.getEvent();
        logger.info("Processing Report generation for request: {}", request.getId());

        return serializer.withRequest(request)
            .toEntity(Report.class)
            .withErrorHandler((error, entity) -> {
                logger.error("Failed to extract entity: {}", error.getMessage(), error);
                return new ErrorInfo("TO_ENTITY_ERROR", "Failed to extract entity: " + error.getMessage());
            })
            .validate(this::isValidEntity, "Invalid entity state")
            .map(this::processEntityLogic)
            .complete();
    }

    @Override
    public boolean supports(OperationSpecification modelSpec) {
        return className.equalsIgnoreCase(modelSpec.operationName());
    }

    private boolean isValidEntity(Report entity) {
        return entity != null && entity.getReportId() != null;
    }

    private Report processEntityLogic(ProcessorSerializer.ProcessorEntityExecutionContext<Report> context) {
        Report entity = context.entity();
        
        try {
            // Generate report content based on type
            String reportContent;
            
            switch (entity.getReportType()) {
                case "SUMMARY":
                    reportContent = generateSummaryReport(entity);
                    break;
                case "DETAILED":
                    reportContent = generateDetailedReport(entity);
                    break;
                case "FILTERED":
                    reportContent = generateFilteredReport(entity);
                    break;
                default:
                    reportContent = generateDefaultReport(entity);
                    break;
            }
            
            // In a real implementation, we would store the report content
            // in a file system, database, or other storage mechanism
            // For this implementation, we'll just log the successful generation
            
            logger.info("Successfully generated {} report {}", entity.getReportType(), entity.getReportId());
            logger.debug("Report content preview: {}", reportContent.substring(0, Math.min(200, reportContent.length())));
            
        } catch (Exception e) {
            logger.error("Failed to generate report {}: {}", entity.getReportId(), e.getMessage(), e);
            throw new RuntimeException("Report generation failed: " + e.getMessage(), e);
        }

        return entity;
    }
    
    private String generateSummaryReport(Report report) {
        StringBuilder content = new StringBuilder();
        content.append("=== BOOKING SUMMARY REPORT ===\n");
        content.append("Report ID: ").append(report.getReportId()).append("\n");
        content.append("Report Name: ").append(report.getReportName()).append("\n");
        content.append("Generated: ").append(report.getGeneratedAt()).append("\n");
        content.append("Generated By: ").append(report.getGeneratedBy()).append("\n\n");
        
        content.append("=== SUMMARY METRICS ===\n");
        content.append("Total Bookings: ").append(report.getTotalBookings()).append("\n");
        content.append("Total Revenue: $").append(report.getTotalRevenue()).append("\n");
        content.append("Average Price: $").append(report.getAveragePrice()).append("\n");
        content.append("Bookings with Deposit Paid: ").append(report.getDepositPaidCount()).append("\n");
        content.append("Bookings with Deposit Unpaid: ").append(report.getDepositUnpaidCount()).append("\n");
        
        if (report.getDateRange() != null) {
            content.append("Date Range: ").append(report.getDateRange()).append("\n");
        }
        
        return content.toString();
    }
    
    private String generateDetailedReport(Report report) {
        StringBuilder content = new StringBuilder();
        content.append("=== DETAILED BOOKING REPORT ===\n");
        content.append("Report ID: ").append(report.getReportId()).append("\n");
        content.append("Report Name: ").append(report.getReportName()).append("\n");
        content.append("Generated: ").append(report.getGeneratedAt()).append("\n");
        content.append("Generated By: ").append(report.getGeneratedBy()).append("\n\n");
        
        content.append("=== DETAILED METRICS ===\n");
        content.append("Total Bookings: ").append(report.getTotalBookings()).append("\n");
        content.append("Total Revenue: $").append(report.getTotalRevenue()).append("\n");
        content.append("Average Price: $").append(report.getAveragePrice()).append("\n");
        content.append("Bookings with Deposit Paid: ").append(report.getDepositPaidCount()).append("\n");
        content.append("Bookings with Deposit Unpaid: ").append(report.getDepositUnpaidCount()).append("\n");
        
        if (report.getFilterCriteria() != null) {
            content.append("Applied Filters: ").append(report.getFilterCriteria()).append("\n");
        }
        
        // In a real implementation, this would include individual booking details
        content.append("\n=== BOOKING DETAILS ===\n");
        content.append("(Individual booking details would be listed here)\n");
        
        return content.toString();
    }
    
    private String generateFilteredReport(Report report) {
        StringBuilder content = new StringBuilder();
        content.append("=== FILTERED BOOKING REPORT ===\n");
        content.append("Report ID: ").append(report.getReportId()).append("\n");
        content.append("Report Name: ").append(report.getReportName()).append("\n");
        content.append("Generated: ").append(report.getGeneratedAt()).append("\n");
        content.append("Generated By: ").append(report.getGeneratedBy()).append("\n\n");
        
        content.append("=== FILTER CRITERIA ===\n");
        if (report.getFilterCriteria() != null) {
            content.append("Applied Filters: ").append(report.getFilterCriteria()).append("\n");
        } else {
            content.append("No filters applied\n");
        }
        
        content.append("\n=== FILTERED RESULTS ===\n");
        content.append("Total Bookings: ").append(report.getTotalBookings()).append("\n");
        content.append("Total Revenue: $").append(report.getTotalRevenue()).append("\n");
        content.append("Average Price: $").append(report.getAveragePrice()).append("\n");
        content.append("Bookings with Deposit Paid: ").append(report.getDepositPaidCount()).append("\n");
        content.append("Bookings with Deposit Unpaid: ").append(report.getDepositUnpaidCount()).append("\n");
        
        return content.toString();
    }
    
    private String generateDefaultReport(Report report) {
        return generateSummaryReport(report);
    }
}
