package com.java_template.application.processor;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.java_template.application.entity.rawpet.version_1.RawPet;
import com.java_template.application.entity.transformedpet.version_1.TransformedPet;
import com.java_template.common.serializer.ProcessorSerializer;
import com.java_template.common.serializer.SerializerFactory;
import com.java_template.common.workflow.CyodaEventContext;
import com.java_template.common.workflow.CyodaProcessor;
import com.java_template.common.workflow.OperationSpecification;
import com.java_template.common.service.EntityService;
import com.java_template.common.util.Condition;
import com.java_template.common.util.SearchConditionRequest;
import org.cyoda.cloud.api.event.processing.EntityProcessorCalculationRequest;
import org.cyoda.cloud.api.event.processing.EntityProcessorCalculationResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.Iterator;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;

@Component
public class TransformRawPetProcessor implements CyodaProcessor {

    private static final Logger logger = LoggerFactory.getLogger(TransformRawPetProcessor.class);
    private final String className = this.getClass().getSimpleName();
    private final ProcessorSerializer serializer;
    private final EntityService entityService;
    private final ObjectMapper objectMapper;

    public TransformRawPetProcessor(SerializerFactory serializerFactory, EntityService entityService, ObjectMapper objectMapper) {
        this.serializer = serializerFactory.getDefaultProcessorSerializer();
        this.entityService = entityService;
        this.objectMapper = objectMapper;
    }

    @Override
    public EntityProcessorCalculationResponse process(CyodaEventContext<EntityProcessorCalculationRequest> context) {
        EntityProcessorCalculationRequest request = context.getEvent();
        logger.info("Processing TransformRawPet for request: {}", request.getId());

        return serializer.withRequest(request)
            .toEntity(RawPet.class)
            .validate(this::isValidEntity, "Invalid entity state")
            .map(this::processEntityLogic)
            .complete();
    }

    @Override
    public boolean supports(OperationSpecification modelSpec) {
        return className.equalsIgnoreCase(modelSpec.operationName());
    }

    private boolean isValidEntity(RawPet entity) {
        return entity != null && ("STORED".equals(entity.getState()) || "MARKED_FOR_TRANSFORM".equals(entity.getState()));
    }

    private RawPet processEntityLogic(ProcessorSerializer.ProcessorEntityExecutionContext<RawPet> context) {
        RawPet raw = context.entity();
        try {
            // Parse payload safely
            JsonNode payload = null;
            try {
                payload = objectMapper.readTree(raw.getPayload());
            } catch (Exception e) {
                logger.warn("Malformed RawPet payload for rawId {} -> marking RAW_FAILED", raw.getRawId());
                raw.setState("RAW_FAILED");
                return raw;
            }

            // Map to TransformedPet
            TransformedPet tp = new TransformedPet();
            // id is generated by downstream store so leave null
            String name = null;
            if (payload.has("petName")) name = payload.get("petName").asText(null);
            if (name == null && payload.has("name")) name = payload.get("name").asText(null);
            if (name == null) name = "unknown";
            tp.setName(name);

            String species = payload.has("species") ? payload.get("species").asText(null) : null;
            if (species != null) tp.setSpecies(species.toLowerCase());

            if (payload.has("breed")) tp.setBreed(payload.get("breed").asText(null));
            if (raw.getCategoryId() != null) tp.setCategoryId(raw.getCategoryId());

            String status = raw.getStatus();
            String availability = "Unknown";
            if (status != null) {
                switch (status.toLowerCase()) {
                    case "available": availability = "Available now"; break;
                    case "pending": availability = "Pending"; break;
                    case "sold": availability = "Not available"; break;
                    default: availability = status;
                }
            }
            tp.setAvailability(availability);

            tp.setSourceMeta((raw.getRawId()==null?"":raw.getRawId()) + "|" + (raw.getIngestedAt()==null?Instant.now().toString():raw.getIngestedAt()));
            tp.setSearchRequestId(raw.getSearchRequestId());
            tp.setCreatedAt(Instant.now().toString());
            tp.setState("TP_CREATED");

            // Persist TransformedPet idempotently: dedupe by sourceMeta
            SearchConditionRequest condition = SearchConditionRequest.group("AND",
                Condition.of("$.sourceMeta", "EQUALS", tp.getSourceMeta())
            );
            CompletableFuture<com.fasterxml.jackson.databind.node.ArrayNode> existingFuture = entityService.getItemsByCondition(
                TransformedPet.ENTITY_NAME, String.valueOf(TransformedPet.ENTITY_VERSION), condition, true
            );
            com.fasterxml.jackson.databind.node.ArrayNode existing = existingFuture.get();
            if (existing != null && existing.size() > 0) {
                logger.info("TransformedPet for sourceMeta {} already exists - skipping creation", tp.getSourceMeta());
            } else {
                try {
                    entityService.addItem(TransformedPet.ENTITY_NAME, String.valueOf(TransformedPet.ENTITY_VERSION), tp);
                    logger.info("Created TransformedPet for rawId {}", raw.getRawId());
                } catch (Exception e) {
                    logger.error("Failed to create TransformedPet for rawId {}", raw.getRawId(), e);
                    raw.setState("RAW_FAILED");
                    return raw;
                }
            }

            // mark raw as transformed
            raw.setTransformedAt(Instant.now().toString());
            raw.setState("TRANSFORMED");
            logger.info("RawPet {} transformed", raw.getRawId());

        } catch (Exception e) {
            logger.error("Error transforming RawPet {}", raw.getRawId(), e);
            raw.setState("RAW_FAILED");
        }
        return raw;
    }
}
